artifact

diff --git a/artifact/_scripts/save_analysis b/artifact/_scripts/save_analysis
--- a/artifact/_scripts/save_analysis
+++ b/artifact/_scripts/save_analysis
@@ -1,5 +1,16 @@
 #!/bin/bash
+exp_type=$1
 
-cd /home/artifact/pacsolve/slurm/analysis_top1000/
+# depending on the exp_type we will run different experiments
 
-Rscript analysis.R
+
+if [ $exp_type == "top1000_comparison" ]; then
+  cd /home/artifact/pacsolve/slurm/analysis_top1000/
+  Rscript analysis.R
+elif [ $exp_type == "vuln_tarballs" ]; then
+  cd /home/artifact/pacsolve/slurm/analysis_top1000/
+else
+    echo "Invalid exp type: $exp_type"
+    exit 1
+fi
+
